Document: mensa-cli
Title: Debian mensa-cli Manual
Author: <insert document author here>
Abstract: This manual describes what mensa-cli is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mensa-cli/mensa-cli.sgml.gz

Format: postscript
Files: /usr/share/doc/mensa-cli/mensa-cli.ps.gz

Format: text
Files: /usr/share/doc/mensa-cli/mensa-cli.text.gz

Format: HTML
Index: /usr/share/doc/mensa-cli/html/index.html
Files: /usr/share/doc/mensa-cli/html/*.html
